### ISSUE TITLE
Beyond fetch_multi : delegating function call to the backend

### ISSUE THREAD

**Issue by llange** [brutasse/graphite-api#68]
Hello,

I'm writing a finder / backend for a storage engine which already has some functions and aggregations implemented. (I target KairosDB, but it should be the same for others like InfluxDB, etc...)

What about delegating part of the (or the whole) request to the underlying backend when those functions are implemented in the backend ?
In my case it would really speed up the query.

It would require enhancing the plugin interface to specify which functions are ok to delegate ; and there would need some query rewrite as most of the storage engines out there do not understand wildcards (which, I think, is graphite's interesting point).

Any thoughts about it ?

**Comment by pkittenis** [comment]
(Might be necro bump, sorry)

This would be interesting, though not sure how feasible.

Have written an InfluxDB finder that has something similar though instead of delegation of _all_ functions to influx, it allows user to configure a `<graphite metric path pattern>: <influx aggregation function>` per [Aggregation configuration](https://github.com/InfluxGraph/influxgraph#aggregation-function-configuration)

The finder then uses the configured aggregation to write the query. This, however, does not apply when aggregation functions are part of the API query, only when they are configured server side.

This is modeled after `storage-aggregation.conf` which does the same for graphite aggregation functions.

What I think would be feasible would be:

* Pass through desired aggregation function on call to `fetch` and `fetch_multi`
* Allow  finder to return back a flag to graphite-api to tell it not to apply its own aggregation on top of that

Flag can default to `False` which is current behaviour, unless overridden by custom finder.

The call to fetch* is the only entry point into a finder so by necessity any aggregation that the finder needs to apply needs to be provided through that entry point. Request delegation is not feasible without knowledge of the data store's  API which is implemented entirely  within the custom finder.

Aggregation function could be either from API query or from server side configuration like the above. The finder implementation can then use that information to do its aggregation and tell graphite-api to skip applying its own aggregation.

If this sounds useful I can provide some code for review/feedback.

**Comment by llange** [comment]
Even though I'm not using KairosDB anymore, I'd be happy to have a look a this code if you mind sharing it somehwere.
In the meantime, I'm closing the issue - which should not prevent anyone to comment on it and reopen if needed - as it's four year old and still open :-)
